import { brandRunbookExamples } from "@/lib/brand/runbook-examples";
import type { BrandProfile } from "@/lib/brand/types";

export const CLINICLY: BrandProfile = {
  id: "clinicly",
  productName: "Clinicly",
  industry: "healthcare",
  operatorRole: "Revenue cycle",
  operatorEmail: "avery.quinn@clinicly.example",
  workspaceName: "Clinicly Workspace",
  tagline: "Membership and statement operations for a fictional healthcare provider.",
  tokens: {
    light: {
      indigo: "#0f766e",
      indigo600: "#0f766e",
      indigo500: "#14b8a6",
      indigoSoft: "#ccfbf1",
      indigoPage: "#5eead4",
      indigoPageSoft: "#ccfbf1",
    },
    dark: {
      indigo: "#2dd4bf",
      indigo600: "#14b8a6",
      indigo500: "#5eead4",
      indigoSoft: "#134e4a",
      indigoPage: "#115e59",
      indigoPageSoft: "#042f2e",
    },
  },
  copy: {
    dashboardSubtitle: "Clinicly Workspace · catalog $49 / $99 / $249 · clock frozen 23 Aug 2026.",
    invoicesDescription:
      "Seeded membership statements only. Amounts are Starter $49, Growth $99, or Scale $249 — never a custom figure.",
    invoicesEmpty:
      "Clear the filter or search. The seed still has Harborline Medical Group, Cedarwell Family Practice, Quarrypine Orthopedics, and the rest of the Clinicly book.",
    collectionsEyebrow: "Dunning",
    collectionsDescription:
      "Overdue statements against the frozen 23 Aug 2026 clock. Amounts stay on the catalog — Starter $49, Growth $99, Scale $249.",
    collectionsEmptyTitle: "No overdue statements",
    collectionsEmptyBody: "Nothing is past due in this book. Open statements still sit on the invoice list.",
    disputesDescription:
      "Claim-credit suggestions must stay inside the catalog. The detail page and resolve API are unfinished — that is the Agent seam.",
    settingsDescription: "Clinicly is fiction. Keep the catalog honest and the practice names invented.",
    sidebarBlurb:
      "Overdue statements and dunning notes sit in the collections queue. Catalog stays $49 / $99 / $249.",
    searchPlaceholder: "Search statements, practices, dsp_… or inv_…",
    lineItem: (planLabel) => `${planLabel} membership · monthly`,
    extraInvoiceMemo: (planLabel, customerName) =>
      `${planLabel} membership — August cycle for ${customerName}.`,
  },
  customers: [
    {
      id: "cus_harborline",
      name: "Harborline Medical Group",
      contactName: "Jordan Hale",
      email: "billing@harborlinemed.example",
      plan: "GROWTH",
    },
    {
      id: "cus_cedarwell",
      name: "Cedarwell Family Practice",
      contactName: "Remy Sato",
      email: "hello@cedarwellfp.example",
      plan: "STARTER",
    },
    {
      id: "cus_quarrypine",
      name: "Quarrypine Orthopedics",
      contactName: "Ellis Marlow",
      email: "accounts@quarrypineortho.example",
      plan: "SCALE",
    },
    {
      id: "cus_brightwell",
      name: "Brightwell Imaging",
      contactName: "Priya Nader",
      email: "ops@brightwellimaging.example",
      plan: "GROWTH",
    },
    {
      id: "cus_oakiron",
      name: "Oakiron Dental",
      contactName: "Chris Bellamy",
      email: "billing@oakirondental.example",
      plan: "STARTER",
    },
    {
      id: "cus_fieldnote",
      name: "Fieldnote Women's Clinic",
      contactName: "Sam Ortez",
      email: "ledger@fieldnoteclinic.example",
      plan: "SCALE",
    },
    {
      id: "cus_silverpine",
      name: "Silverpine Pediatrics",
      contactName: "Noor Voss",
      email: "pay@silverpinepeds.example",
      plan: "GROWTH",
    },
    {
      id: "cus_mapleember",
      name: "Maple Ember PT",
      contactName: "Dana Ruiz",
      email: "hello@mapleemberpt.example",
      plan: "STARTER",
    },
    {
      id: "cus_tidewatch",
      name: "Tidewatch Community Health",
      contactName: "Keir Anand",
      email: "billing@tidewatchhealth.example",
      plan: "SCALE",
    },
    {
      id: "cus_copperleaf",
      name: "Copperleaf Dermatology",
      contactName: "Lila Shore",
      email: "studio@copperleafderm.example",
      plan: "GROWTH",
    },
  ],
  extraAccounts: [
    {
      customerId: "cus_northstarfab",
      invoiceId: "inv_2001",
      invoiceNumber: "INV-2001",
      name: "Northstar Surgical Group",
      segment: "Enterprise",
      plan: "GROWTH",
      contactName: "Mara Ellison",
      email: "ap@northstarsurgical.example",
    },
    {
      customerId: "cus_northstarlog",
      invoiceId: "inv_2002",
      invoiceNumber: "INV-2002",
      name: "North Star Rehab Network",
      segment: "Enterprise",
      plan: "GROWTH",
      contactName: "Devan Kohl",
      email: "billing@northstarrehab.example",
    },
    {
      customerId: "cus_alderbio",
      invoiceId: "inv_2003",
      invoiceNumber: "INV-2003",
      name: "Alder BioClinic",
      segment: "Strategic",
      plan: "SCALE",
      contactName: "Ines Beaufort",
      email: "finance@alderbioclinic.example",
    },
    {
      customerId: "cus_juniperpw",
      invoiceId: "inv_2004",
      invoiceNumber: "INV-2004",
      name: "Linden County Health",
      segment: "Public Sector",
      plan: "STARTER",
      contactName: "Ray Okafor",
      email: "accounts@lindencountyhealth.example",
    },
    {
      customerId: "cus_helioretail",
      invoiceId: "inv_2005",
      invoiceNumber: "INV-2005",
      name: "Helio Eye Care",
      segment: "Enterprise",
      plan: "GROWTH",
      contactName: "Sanne Vos",
      email: "ap@helioeyecare.example",
    },
    {
      customerId: "cus_cedarhealth",
      invoiceId: "inv_2006",
      invoiceNumber: "INV-2006",
      name: "Cedar Health Network",
      segment: "Strategic",
      plan: "SCALE",
      contactName: "Toni Merced",
      email: "payables@cedarhealth.example",
    },
    {
      customerId: "cus_velaenergy",
      invoiceId: "inv_2007",
      invoiceNumber: "INV-2007",
      name: "Vela Wellness",
      segment: "Enterprise",
      plan: "GROWTH",
      contactName: "Bram Whitlock",
      email: "billing@velawellness.example",
    },
    {
      customerId: "cus_kestrelmob",
      invoiceId: "inv_2008",
      invoiceNumber: "INV-2008",
      name: "Kestrel Mobility Clinic",
      segment: "Growth",
      plan: "STARTER",
      contactName: "Freja Lindqvist",
      email: "ap@kestrelmobilityclinic.example",
    },
    {
      customerId: "cus_blueharbor",
      invoiceId: "inv_2009",
      invoiceNumber: "INV-2009",
      name: "Blue Harbor Benefits",
      segment: "Strategic",
      plan: "SCALE",
      contactName: "Curtis Alba",
      email: "vendors@blueharborbenefits.example",
    },
    {
      customerId: "cus_stonebridge",
      invoiceId: "inv_2010",
      invoiceNumber: "INV-2010",
      name: "Stonebridge Imaging",
      segment: "Growth",
      plan: "STARTER",
      contactName: "Petra Hollis",
      email: "accounts@stonebridgeimaging.example",
    },
    {
      customerId: "cus_lumenedu",
      invoiceId: "inv_2011",
      invoiceNumber: "INV-2011",
      name: "Lumen Student Health",
      segment: "Public Sector",
      plan: "STARTER",
      contactName: "Marisol Duarte",
      email: "finance@lumenstudenthealth.example",
    },
    {
      customerId: "cus_orchidfoods",
      invoiceId: "inv_2012",
      invoiceNumber: "INV-2012",
      name: "Orchid Nutrition Clinic",
      segment: "Enterprise",
      plan: "GROWTH",
      contactName: "Hana Sook",
      email: "ap@orchidnutrition.example",
    },
    {
      customerId: "cus_summitaero",
      invoiceId: "inv_2013",
      invoiceNumber: "INV-2013",
      name: "Summit Aero Medical",
      segment: "Strategic",
      plan: "SCALE",
      contactName: "Callum Reyes",
      email: "payables@summitaeromed.example",
    },
    {
      customerId: "cus_redwoodcomp",
      invoiceId: "inv_2014",
      invoiceNumber: "INV-2014",
      name: "Redwood Community Clinic",
      segment: "Growth",
      plan: "STARTER",
      contactName: "Josie Tran",
      email: "billing@redwoodclinic.example",
    },
  ],
  invoiceMemos: {
    inv_1041: "Monthly Growth membership for Harborline Medical Group.",
    inv_1042: "Starter membership — July cycle.",
    inv_1043: "Scale membership. Practice opened a plan-mismatch dispute.",
    inv_1044: "Growth membership — July cycle.",
    inv_1045: "Starter membership for Oakiron Dental.",
    inv_1046: "Scale membership — July cycle.",
    inv_1047: "Growth membership. Duplicate-charge dispute is open.",
    inv_1048: "Draft — waiting on a purchase-order number.",
    inv_1049: "Scale membership. Care-window dispute needs review.",
    inv_1050: "Growth membership. Historical dispute was accepted.",
    inv_1051: "Voided — upgraded to Growth the same week.",
    inv_1053: "Growth membership — prior cycle for Harborline Medical Group.",
    inv_1054: "Starter membership — July cycle for Cedarwell Family Practice.",
    inv_1055: "Scale membership — paid mid-August.",
    inv_1056: "Growth membership — June cycle for Harborline Medical Group.",
    inv_1057: "Growth membership — August cycle, paid early.",
    inv_1052: "Mid-cycle upgrade from Starter to Growth.",
  },
  disputeCopy: {
    dsp_1043: {
      reason:
        "Billed on Scale membership. The signed order is Growth. The practice is claiming back more than this statement charges.",
    },
    dsp_1047: { reason: "Duplicate charge for the same coverage period." },
    dsp_1049: { reason: "Care window has not started. Asking to hold the statement." },
    dsp_1041: { reason: "Tax-exempt certificate is on file. Please confirm the line." },
    dsp_1050: {
      reason: "Wrong membership last cycle. Credit issued at the Growth price.",
      reviewerNote: "Accepted. Credit equals the Growth catalog price of $99.",
    },
  },
  runbookExamples: brandRunbookExamples({
    productName: "Clinicly",
    planExample:
      "/plan I want a new feature to update the practice email in the statement detail customer card. Don’t implement email validation.",
    redactExample:
      "Redact the practice email in the UI. The first two characters and domain are plaintext.",
    interruptExample:
      "Redact the practice email in the UI. Show it in plaintext if I click an icon. Stop every time you change a file for me to review.",
    testRuleExample:
      "Add a new feature to show the current cap for claim credit. Make clear which API you’re referencing.",
    cliAskExample:
      'agent --trust --mode=ask "Explain why dsp_1043 shows a $400 suggested credit even though the stored credit and v2 response are $249. Cite the source files and do not edit anything."',
  }),
};
