import { brandRunbookExamples } from "@/lib/brand/runbook-examples";
import type { BrandProfile } from "@/lib/brand/types";

export const SAASLY: BrandProfile = {
  id: "saasly",
  productName: "SaaSly",
  industry: "SaaS",
  operatorRole: "Billing ops",
  operatorEmail: "avery.quinn@saasly.example",
  workspaceName: "SaaSly Workspace",
  tagline: "Subscription billing operations for a fictional SaaS company.",
  tokens: {
    light: {
      indigo: "#4f46e5",
      indigo600: "#4f46e5",
      indigo500: "#6366f1",
      indigoSoft: "#eef2ff",
      indigoPage: "#c7d2fe",
      indigoPageSoft: "#e0e7ff",
    },
    dark: {
      indigo: "#818cf8",
      indigo600: "#6366f1",
      indigo500: "#a5b4fc",
      indigoSoft: "#222454",
      indigoPage: "#3730a3",
      indigoPageSoft: "#1e1b4b",
    },
  },
  copy: {
    dashboardSubtitle: "SaaSly Workspace · catalog $49 / $99 / $249 · clock frozen 23 Aug 2026.",
    invoicesDescription:
      "Seeded folios only. Amounts are Starter $49, Growth $99, or Scale $249 — never a custom figure.",
    invoicesEmpty:
      "Clear the filter or search. The seed still has Acme North, Riverstone Labs, Cobalt Goods, and the rest of the SaaSly book.",
    collectionsEyebrow: "Dunning",
    collectionsDescription:
      "Overdue folios against the frozen 23 Aug 2026 clock. Amounts stay on the catalog — Starter $49, Growth $99, Scale $249.",
    collectionsEmptyTitle: "No overdue invoices",
    collectionsEmptyBody: "Nothing is past due in this book. Open invoices still sit on the invoice list.",
    disputesDescription:
      "Credit suggestions must stay inside the catalog. The detail page and resolve API are unfinished — that is the Agent seam.",
    settingsDescription: "SaaSly is fiction. Keep the catalog honest and the names invented.",
    sidebarBlurb:
      "Overdue invoices and dunning notes sit in the collections queue. Catalog stays $49 / $99 / $249.",
    searchPlaceholder: "Search invoices, customers, dsp_… or inv_…",
    lineItem: (planLabel) => `${planLabel} plan · monthly`,
    extraInvoiceMemo: ({ planLabel, customerName }) =>
      `${planLabel} plan — August cycle for ${customerName}.`,
  },
  customers: [
    {
      id: "cus_harborline",
      name: "Acme North",
      contactName: "Jordan Hale",
      email: "billing@acmenorth.example",
      plan: "GROWTH",
    },
    {
      id: "cus_cedarwell",
      name: "Riverstone Labs",
      contactName: "Remy Sato",
      email: "hello@riverstone.example",
      plan: "STARTER",
    },
    {
      id: "cus_quarrypine",
      name: "Cobalt Goods",
      contactName: "Ellis Marlow",
      email: "accounts@cobaltgoods.example",
      plan: "SCALE",
    },
    {
      id: "cus_brightwell",
      name: "Brightwell Labs",
      contactName: "Priya Nader",
      email: "ops@brightwell.example",
      plan: "GROWTH",
    },
    {
      id: "cus_oakiron",
      name: "Oakiron Supply",
      contactName: "Chris Bellamy",
      email: "billing@oakiron.example",
      plan: "STARTER",
    },
    {
      id: "cus_fieldnote",
      name: "Fieldnote Press",
      contactName: "Sam Ortez",
      email: "ledger@fieldnote.example",
      plan: "SCALE",
    },
    {
      id: "cus_silverpine",
      name: "Silverpine Outfitters",
      contactName: "Noor Voss",
      email: "pay@silverpine.example",
      plan: "GROWTH",
    },
    {
      id: "cus_mapleember",
      name: "Maple & Ember Co",
      contactName: "Dana Ruiz",
      email: "hello@mapleember.example",
      plan: "STARTER",
    },
    {
      id: "cus_tidewatch",
      name: "Tidewatch Logistics",
      contactName: "Keir Anand",
      email: "billing@tidewatch.example",
      plan: "SCALE",
    },
    {
      id: "cus_copperleaf",
      name: "Copperleaf Atelier",
      contactName: "Lila Shore",
      email: "studio@copperleaf.example",
      plan: "GROWTH",
    },
  ],
  extraAccounts: [
    {
      customerId: "cus_northstarfab",
      invoiceId: "inv_2001",
      invoiceNumber: "INV-2001",
      name: "Northstar Fabrication",
      segment: "Enterprise",
      plan: "GROWTH",
      contactName: "Mara Ellison",
      email: "ap@northstarfab.example",
    },
    {
      customerId: "cus_northstarlog",
      invoiceId: "inv_2002",
      invoiceNumber: "INV-2002",
      name: "North Star Logistics",
      segment: "Enterprise",
      plan: "GROWTH",
      contactName: "Devan Kohl",
      email: "billing@northstarlogistics.example",
    },
    {
      customerId: "cus_alderbio",
      invoiceId: "inv_2003",
      invoiceNumber: "INV-2003",
      name: "Alder BioSystems",
      segment: "Strategic",
      plan: "SCALE",
      contactName: "Ines Beaufort",
      email: "finance@alderbio.example",
    },
    {
      customerId: "cus_juniperpw",
      invoiceId: "inv_2004",
      invoiceNumber: "INV-2004",
      name: "Juniper Public Works",
      segment: "Public Sector",
      plan: "STARTER",
      contactName: "Ray Okafor",
      email: "accounts@juniperpw.example",
    },
    {
      customerId: "cus_helioretail",
      invoiceId: "inv_2005",
      invoiceNumber: "INV-2005",
      name: "Helio Retail Group",
      segment: "Enterprise",
      plan: "GROWTH",
      contactName: "Sanne Vos",
      email: "ap@helioretail.example",
    },
    {
      customerId: "cus_cedarhealth",
      invoiceId: "inv_2006",
      invoiceNumber: "INV-2006",
      name: "Cedar Health Network",
      segment: "Strategic",
      plan: "SCALE",
      contactName: "Toni Merced",
      email: "payables@cedarhealth.example",
    },
    {
      customerId: "cus_velaenergy",
      invoiceId: "inv_2007",
      invoiceNumber: "INV-2007",
      name: "Vela Energy Systems",
      segment: "Enterprise",
      plan: "GROWTH",
      contactName: "Bram Whitlock",
      email: "billing@velaenergy.example",
    },
    {
      customerId: "cus_kestrelmob",
      invoiceId: "inv_2008",
      invoiceNumber: "INV-2008",
      name: "Kestrel Mobility",
      segment: "Growth",
      plan: "STARTER",
      contactName: "Freja Lindqvist",
      email: "ap@kestrelmobility.example",
    },
    {
      customerId: "cus_blueharbor",
      invoiceId: "inv_2009",
      invoiceNumber: "INV-2009",
      name: "Blue Harbor Bank",
      segment: "Strategic",
      plan: "SCALE",
      contactName: "Curtis Alba",
      email: "vendors@blueharborbank.example",
    },
    {
      customerId: "cus_stonebridge",
      invoiceId: "inv_2010",
      invoiceNumber: "INV-2010",
      name: "Stonebridge Media",
      segment: "Growth",
      plan: "STARTER",
      contactName: "Petra Hollis",
      email: "accounts@stonebridgemedia.example",
    },
    {
      customerId: "cus_lumenedu",
      invoiceId: "inv_2011",
      invoiceNumber: "INV-2011",
      name: "Lumen Education",
      segment: "Public Sector",
      plan: "STARTER",
      contactName: "Marisol Duarte",
      email: "finance@lumenedu.example",
    },
    {
      customerId: "cus_orchidfoods",
      invoiceId: "inv_2012",
      invoiceNumber: "INV-2012",
      name: "Orchid Foods",
      segment: "Enterprise",
      plan: "GROWTH",
      contactName: "Hana Sook",
      email: "ap@orchidfoods.example",
    },
    {
      customerId: "cus_summitaero",
      invoiceId: "inv_2013",
      invoiceNumber: "INV-2013",
      name: "Summit Aero",
      segment: "Strategic",
      plan: "SCALE",
      contactName: "Callum Reyes",
      email: "payables@summitaero.example",
    },
    {
      customerId: "cus_redwoodcomp",
      invoiceId: "inv_2014",
      invoiceNumber: "INV-2014",
      name: "Redwood Components",
      segment: "Growth",
      plan: "STARTER",
      contactName: "Josie Tran",
      email: "billing@redwoodcomponents.example",
    },
  ],
  invoiceMemos: {
    inv_1041: "Monthly Growth seat for Acme North.",
    inv_1042: "Starter plan — July cycle.",
    inv_1043: "Scale plan. Customer opened a plan-mismatch dispute.",
    inv_1044: "Growth plan — July cycle.",
    inv_1045: "Starter plan for Oakiron Supply.",
    inv_1046: "Scale plan — July cycle.",
    inv_1047: "Growth plan. Duplicate-charge dispute is open.",
    inv_1048: "Draft — waiting on a purchase order number.",
    inv_1049: "Scale plan. Service-window dispute needs review.",
    inv_1050: "Growth plan. Historical dispute was accepted.",
    inv_1051: "Voided — upgraded to Growth the same week.",
    inv_1053: "Growth plan — prior cycle for Acme North.",
    inv_1054: "Starter plan — July cycle for Riverstone Labs.",
    inv_1055: "Scale plan — paid mid-August.",
    inv_1056: "Growth plan — June cycle for Acme North.",
    inv_1057: "Growth plan — August cycle, paid early.",
    inv_1052: "Mid-cycle upgrade from Starter to Growth.",
  },
  disputeCopy: {
    dsp_1043: {
      reason:
        "Billed on Scale. The signed order is Growth. Customer is claiming back more than this invoice charges.",
    },
    dsp_1047: { reason: "Duplicate charge for the same service period." },
    dsp_1049: { reason: "Service window has not started. Asking to hold the invoice." },
    dsp_1041: { reason: "Tax-exempt certificate is on file. Please confirm the line." },
    dsp_1050: {
      reason: "Wrong plan last cycle. Credit issued at the Growth price.",
      reviewerNote: "Accepted. Credit equals the Growth catalog price of $99.",
    },
  },
  runbookExamples: brandRunbookExamples({
    productName: "SaaSly",
    planExample:
      "/plan I want a new feature to update the customer email in the invoice detail customer card. Don’t implement email validation.",
    redactExample:
      "Redact the customer email in the UI. The first two characters and domain are plaintext.",
    interruptExample:
      "Redact the customer email in the UI. Show it in plaintext if I click an icon. Stop every time you change a file for me to review.",
    testRuleExample:
      "Add a new feature to show the current cap for dispute credit. Make clear which API you’re referencing.",
    cliAskExample:
      'agent --trust --mode=ask "Explain why dsp_1043 shows a $400 suggested credit even though the stored credit and v2 response are $249. Cite the source files and do not edit anything."',
  }),
};
